# Generated by Django 2.2.5 on 2019-09-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FamilyMember',
            new_name='Person',
        ),
        migrations.AlterField(
            model_name='family',
            name='community',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='family',
            name='country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='family',
            name='province',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='family',
            name='region',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
