# Generated by Django 2.2.5 on 2019-10-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20191001_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='Food_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='crop',
            name='food_grp',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
