# Generated by Django 2.2.11 on 2020-04-19 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_auto_20200418_2259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myStatus',
        ),
    ]
