# Generated by Django 2.2.11 on 2020-04-20 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_auto_20200420_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop_feasibility',
            name='myLocation',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='myApp.Location'),
        ),
    ]
