# Generated by Django 2.2.11 on 2020-04-25 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_crop_feasibility_mylocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop_Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food_grp', models.CharField(max_length=200)),
                ('Food_name', models.CharField(max_length=200)),
                ('myCountry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.Countries')),
                ('myFCT', models.ForeignKey(default=436, on_delete=django.db.models.deletion.CASCADE, to='myApp.FCT', to_field='food_item_id')),
            ],
        ),
    ]
