# Generated by Django 2.2.11 on 2020-04-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_crop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fct',
            name='Food_grp_unicef',
            field=models.CharField(default='non-category', max_length=200),
        ),
    ]
