# Generated by Django 2.2.11 on 2020-04-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_fct_food_grp_unicef'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop_name',
            name='myCountry',
        ),
        migrations.AddField(
            model_name='crop_name',
            name='myCountryName',
            field=models.CharField(default='ETH', max_length=200),
        ),
    ]
