# Generated by Django 2.2.11 on 2020-05-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_crop_individual_share_prod_buy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop_name',
            name='Food_name',
            field=models.CharField(max_length=201),
        ),
    ]
