# Generated by Django 2.2.5 on 2019-10-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_auto_20191008_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='feas_workload',
            field=models.IntegerField(choices=[(1, 'no'), (2, 'maybe no'), (3, 'maybe yes'), (4, 'yes')], default=1, verbose_name='feas_workload'),
        ),
    ]
