# Generated by Django 2.2.11 on 2020-05-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_auto_20200501_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop_name',
            name='Food_name',
            field=models.CharField(max_length=200),
        ),
    ]
