# Generated by Django 2.2.5 on 2019-10-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_crop_feas_workload'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='crop_list',
            field=models.CharField(default='0', max_length=1000),
        ),
    ]
