# Generated by Django 2.2.11 on 2020-05-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_auto_20200501_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='nut_group',
            field=models.CharField(choices=[('child 0-23 month', 'child 0-23 month'), ('child 24-59 month', 'child 24-59 month'), ('child 6-9 yr', 'child 6-9 yr'), ('adolescent male', 'adolescent male'), ('adolescent female', 'adolescent female'), ('adult male', 'adult male'), ('adult female', 'adult female'), ('pregnant', 'pregnant'), ('lactating', 'lactaning')], default='children 6 to 59 month', max_length=200, verbose_name='nut_group'),
        ),
    ]
