# Generated by Django 2.2.5 on 2019-10-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_family_crop_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='feas_DRI',
            field=models.IntegerField(choices=[(0, 'no'), (1, 'maybe no'), (2, 'maybe yes'), (3, 'yes')], default=0, verbose_name='feas_DRI'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='feas_DRI_a',
            field=models.IntegerField(choices=[(0, 'no'), (1, 'maybe no'), (2, 'maybe yes'), (3, 'yes')], default=0, verbose_name='feas_DRI_a'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='feas_DRI_f',
            field=models.IntegerField(choices=[(0, 'no'), (1, 'maybe no'), (2, 'maybe yes'), (3, 'yes')], default=0, verbose_name='feas_DRI_f'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='feas_DRI_p',
            field=models.IntegerField(choices=[(0, 'no'), (1, 'maybe no'), (2, 'maybe yes'), (3, 'yes')], default=0, verbose_name='feas_DRI_p'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='feas_affordability',
            field=models.IntegerField(choices=[(0, 'no'), (1, 'maybe no'), (2, 'maybe yes'), (3, 'yes')], default=0, verbose_name='feas_affordability'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='feas_availability_non',
            field=models.IntegerField(choices=[(0, '0-3 mon'), (1, '4-6 mon'), (2, '7-9 mon'), (3, '10-12 mon')], default=0, verbose_name='feas_availability_non'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='feas_availability_prod',
            field=models.IntegerField(choices=[(0, '0-3 mon'), (1, '4-6 mon'), (2, '7-9 mon'), (3, '10-12 mon')], default=0, verbose_name='feas_availability_prod'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='feas_invest_fixed',
            field=models.IntegerField(choices=[(3, 'no'), (2, 'maybe no'), (1, 'maybe yes'), (0, 'yes')], default=0, verbose_name='feas_invest_fixed'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='feas_invest_variable',
            field=models.IntegerField(choices=[(3, 'no'), (2, 'maybe no'), (1, 'maybe yes'), (0, 'yes')], default=0, verbose_name='feas_invest_variable'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='feas_prod_skill',
            field=models.IntegerField(choices=[(0, 'no'), (1, 'maybe no'), (2, 'maybe yes'), (3, 'yes')], default=0, verbose_name='feas_prod_skill'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='feas_soc_acceptable',
            field=models.IntegerField(choices=[(3, 'no'), (2, 'maybe no'), (1, 'maybe yes'), (0, 'yes')], default=0, verbose_name='feas_social_wo'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='feas_soc_acceptable_c5',
            field=models.IntegerField(choices=[(3, 'no'), (2, 'maybe no'), (1, 'maybe yes'), (0, 'yes')], default=0, verbose_name='feas_social_c5'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='feas_soc_acceptable_wo',
            field=models.IntegerField(choices=[(3, 'no'), (2, 'maybe no'), (1, 'maybe yes'), (0, 'yes')], default=0, verbose_name='feas_social_wo'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='feas_storability',
            field=models.IntegerField(choices=[(0, 'no'), (1, 'maybe no'), (2, 'maybe yes'), (3, 'yes')], default=0, verbose_name='feas_storability'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='feas_tech_service',
            field=models.IntegerField(choices=[(0, 'no'), (1, 'maybe no'), (2, 'maybe yes'), (3, 'yes')], default=0, verbose_name='feas_tech_service'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='feas_workload',
            field=models.IntegerField(choices=[(3, 'no'), (2, 'maybe no'), (1, 'maybe yes'), (0, 'yes')], default=0, verbose_name='feas_workload'),
        ),
    ]
