# Generated by Django 2.2.5 on 2019-10-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_family_nutrition_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='country',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='family',
            name='nutrition_target',
            field=models.CharField(max_length=200),
        ),
    ]
