# Generated by Django 2.2.11 on 2020-05-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_auto_20200513_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stepid',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
