# Generated by Django 2.2.11 on 2020-06-29 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0016_profile_stepid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='record_date')),
                ('m1_season', models.IntegerField(default=0, verbose_name='mon01_season')),
                ('m2_season', models.IntegerField(default=0, verbose_name='mon02_season')),
                ('m3_season', models.IntegerField(default=0, verbose_name='mon03_season')),
                ('m4_season', models.IntegerField(default=0, verbose_name='mon04_season')),
                ('m5_season', models.IntegerField(default=0, verbose_name='mon05_season')),
                ('m6_season', models.IntegerField(default=0, verbose_name='mon06_season')),
                ('m7_season', models.IntegerField(default=0, verbose_name='mon07_season')),
                ('m8_season', models.IntegerField(default=0, verbose_name='mon08_season')),
                ('m9_season', models.IntegerField(default=0, verbose_name='mon09_season')),
                ('m10_season', models.IntegerField(default=0, verbose_name='mon10_season')),
                ('m11_season', models.IntegerField(default=0, verbose_name='mon11_season')),
                ('m12_season', models.IntegerField(default=0, verbose_name='mon12_season')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
