# Generated by Django 2.2.5 on 2019-10-27 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0017_auto_20191027_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='m01_m',
            new_name='m1_m',
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='m01_p',
            new_name='m1_p',
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='m02_m',
            new_name='m2_m',
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='m02_p',
            new_name='m2_p',
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='m03_m',
            new_name='m3_m',
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='m03_p',
            new_name='m3_p',
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='m04_m',
            new_name='m4_m',
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='m04_p',
            new_name='m4_p',
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='m05_m',
            new_name='m5_m',
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='m05_p',
            new_name='m5_p',
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='m06_m',
            new_name='m6_m',
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='m06_p',
            new_name='m6_p',
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='m07_m',
            new_name='m7_m',
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='m07_p',
            new_name='m7_p',
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='m08_m',
            new_name='m8_m',
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='m08_p',
            new_name='m8_p',
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='m09_m',
            new_name='m9_m',
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='m09_p',
            new_name='m9_p',
        ),
    ]
