# Generated by Django 2.2.11 on 2020-09-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0018_season_mylocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop_individual',
            name='season',
            field=models.IntegerField(default=0, verbose_name='season'),
        ),
        migrations.AddField(
            model_name='crop_subnational',
            name='s01_avail',
            field=models.IntegerField(default=0, verbose_name='s01_avail'),
        ),
        migrations.AddField(
            model_name='crop_subnational',
            name='s02_avail',
            field=models.IntegerField(default=0, verbose_name='s02_avail'),
        ),
        migrations.AddField(
            model_name='crop_subnational',
            name='s03_avail',
            field=models.IntegerField(default=0, verbose_name='s03_avail'),
        ),
        migrations.AddField(
            model_name='crop_subnational',
            name='s04_avail',
            field=models.IntegerField(default=0, verbose_name='s04_avail'),
        ),
        migrations.AddField(
            model_name='crop_subnational',
            name='s05_avail',
            field=models.IntegerField(default=0, verbose_name='s05_avail'),
        ),
        migrations.AddField(
            model_name='location',
            name='season_count',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
