# Generated by Django 2.2.11 on 2020-09-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0019_season_season_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='season_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='season_count'),
        ),
    ]
