# Generated by Django 2.2.11 on 2020-09-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0020_auto_20200925_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='season_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='season_count'),
        ),
    ]
