# Generated by Django 2.2.11 on 2020-09-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0021_auto_20200925_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='season_name1',
            field=models.CharField(blank=True, default='season1', max_length=50),
        ),
        migrations.AddField(
            model_name='season',
            name='season_name2',
            field=models.CharField(blank=True, default='season2', max_length=50),
        ),
        migrations.AddField(
            model_name='season',
            name='season_name3',
            field=models.CharField(blank=True, default='season3', max_length=50),
        ),
        migrations.AddField(
            model_name='season',
            name='season_name4',
            field=models.CharField(blank=True, default='season4', max_length=50),
        ),
    ]
