# Generated by Django 2.2.11 on 2020-10-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0022_auto_20200930_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='dri',
            name='max_vol',
            field=models.IntegerField(default=200, verbose_name='maxVol'),
        ),
    ]
