# Generated by Django 2.2.11 on 2020-10-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0023_dri_max_vol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop_feasibility',
            name='feas_DRI_a',
            field=models.IntegerField(choices=[(0, 'no'), (1, 'maybe no'), (2, 'maybe yes'), (3, 'yes')], default=0, verbose_name='feas_DRI_a'),
        ),
        migrations.AlterField(
            model_name='crop_feasibility',
            name='feas_DRI_e',
            field=models.IntegerField(choices=[(0, 'no'), (1, 'maybe no'), (2, 'maybe yes'), (3, 'yes')], default=0, verbose_name='feas_DRI'),
        ),
        migrations.AlterField(
            model_name='crop_feasibility',
            name='feas_DRI_f',
            field=models.IntegerField(choices=[(0, 'no'), (1, 'maybe no'), (2, 'maybe yes'), (3, 'yes')], default=0, verbose_name='feas_DRI_f'),
        ),
        migrations.AlterField(
            model_name='crop_feasibility',
            name='feas_DRI_p',
            field=models.IntegerField(choices=[(0, 'no'), (1, 'maybe no'), (2, 'maybe yes'), (3, 'yes')], default=0, verbose_name='feas_DRI_p'),
        ),
        migrations.AlterField(
            model_name='crop_feasibility',
            name='feas_soc_acceptable',
            field=models.IntegerField(choices=[(3, 'no'), (2, 'maybe no'), (1, 'maybe yes'), (0, 'yes')], default=0, verbose_name='feas_social_wo'),
        ),
        migrations.AlterField(
            model_name='crop_feasibility',
            name='feas_soc_acceptable_c5',
            field=models.IntegerField(choices=[(3, 'no'), (2, 'maybe no'), (1, 'maybe yes'), (0, 'yes')], default=0, verbose_name='feas_social_c5'),
        ),
        migrations.AlterField(
            model_name='crop_feasibility',
            name='feas_soc_acceptable_wo',
            field=models.IntegerField(choices=[(3, 'no'), (2, 'maybe no'), (1, 'maybe yes'), (0, 'yes')], default=0, verbose_name='feas_social_wo'),
        ),
    ]
