# Generated by Django 2.2.11 on 2020-10-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0024_auto_20201005_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop_feasibility',
            name='feas_soc_acceptable',
            field=models.IntegerField(choices=[(3, 'no'), (2, 'maybe no'), (1, 'maybe yes'), (0, 'yes')], default=0, verbose_name='feas_social_wo'),
        ),
        migrations.AlterField(
            model_name='crop_feasibility',
            name='feas_soc_acceptable_c5',
            field=models.IntegerField(choices=[(3, 'no'), (2, 'maybe no'), (1, 'maybe yes'), (0, 'yes')], default=0, verbose_name='feas_social_c5'),
        ),
        migrations.AlterField(
            model_name='crop_feasibility',
            name='feas_soc_acceptable_wo',
            field=models.IntegerField(choices=[(3, 'no'), (2, 'maybe no'), (1, 'maybe yes'), (0, 'yes')], default=0, verbose_name='feas_social_wo'),
        ),
    ]
