# Generated by Django 2.2.5 on 2019-11-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0025_person_target_pop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='target_pop',
            field=models.IntegerField(default=0, verbose_name='number'),
        ),
    ]
