# Generated by Django 2.2.5 on 2020-01-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0029_auto_20191113_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GID_0', models.CharField(max_length=200)),
                ('NAME_0', models.CharField(max_length=200)),
                ('GID_1', models.CharField(max_length=200)),
                ('NAME_1', models.CharField(max_length=200)),
                ('GID_2', models.CharField(max_length=200)),
                ('NAME_2', models.CharField(max_length=200)),
                ('GID_3', models.CharField(max_length=200)),
                ('NAME_3', models.CharField(max_length=200)),
            ],
        ),
    ]
