# Generated by Django 2.2.5 on 2020-01-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0030_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='anemia_rate',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='family',
            name='nutrition_target',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='family',
            name='stunting_rate',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='family',
            name='wasting_rate',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
