# Generated by Django 2.2.14 on 2020-11-18 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0031_auto_20201118_0511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop_feasibility_instant',
            name='myLocation',
        ),
    ]
