# Generated by Django 2.2.5 on 2020-01-28 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0031_auto_20200128_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop_Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('GID_1', models.CharField(max_length=200)),
                ('FCT_id', models.IntegerField(default=1)),
                ('food_grp_id', models.IntegerField(default=1)),
                ('food_item_id', models.IntegerField(default=1)),
                ('Food_grp', models.CharField(max_length=200)),
                ('Food_name', models.CharField(max_length=200)),
                ('suitable_class', models.IntegerField(default=1)),
                ('Hrv_strt', models.IntegerField(default=1)),
                ('Hrv_end', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='record_date')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Crop_AEZ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('FCT_id', models.IntegerField(default=1)),
                ('food_grp_id', models.IntegerField(default=1)),
                ('food_item_id', models.IntegerField(default=1)),
                ('Food_grp', models.CharField(max_length=200)),
                ('Food_name', models.CharField(max_length=200)),
                ('Crop_ref', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='record_date')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
