# Generated by Django 2.2.11 on 2020-11-19 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0032_remove_crop_feasibility_instant_mylocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop_Individual_instant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_scope', models.IntegerField(default=0, verbose_name='target_scope')),
                ('portion_size', models.IntegerField(default=10)),
                ('total_weight', models.IntegerField(default=0)),
                ('count_prod', models.IntegerField(default=0, verbose_name='count_prod')),
                ('count_buy', models.IntegerField(default=0, verbose_name='count_buy')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='record_date')),
                ('myName', models.CharField(default='', max_length=200, verbose_name='myName')),
                ('share_prod_buy', models.IntegerField(default=5, verbose_name='share_prod_buy')),
                ('myFCT', models.ForeignKey(default=436, on_delete=django.db.models.deletion.CASCADE, to='myApp.FCT', to_field='food_item_id')),
            ],
        ),
    ]
