# Generated by Django 2.2.5 on 2020-02-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0032_auto_20200206_0835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dri_aggr',
            old_name='group',
            new_name='nut_group',
        ),
    ]
