# Generated by Django 2.2.5 on 2020-01-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0033_auto_20200128_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='conv_crop_grow',
            field=models.CharField(default='0', max_length=1000),
        ),
        migrations.AddField(
            model_name='family',
            name='conv_crop_mrkt',
            field=models.CharField(default='0', max_length=1000),
        ),
    ]
