# Generated by Django 2.2.11 on 2020-11-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0033_crop_individual_instant'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop_individual_instant',
            name='recepi_id',
            field=models.IntegerField(default=0, verbose_name='recepi_id'),
        ),
    ]
