# Generated by Django 2.2.5 on 2020-02-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0033_auto_20200206_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dri_aggr',
            name='protein',
            field=models.FloatField(default=0, verbose_name='nut_protein'),
        ),
    ]
