# Generated by Django 2.2.5 on 2020-01-30 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0034_auto_20200130_0417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='conv_crop_mrkt',
            new_name='conv_crop_sold',
        ),
    ]
