# Generated by Django 2.2.5 on 2020-01-31 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0035_auto_20200130_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='nut_group',
            field=models.CharField(default='no name', max_length=200, verbose_name='nut_group'),
        ),
        migrations.AddField(
            model_name='person',
            name='nut_question1',
            field=models.IntegerField(choices=[(1, 'answer 1'), (2, 'answer 2'), (3, 'answer 3'), (4, 'answer 4'), (5, 'answer 5')], default=1, verbose_name='nut_question1'),
        ),
        migrations.AddField(
            model_name='person',
            name='nut_question2',
            field=models.IntegerField(choices=[(1, 'answer 1'), (2, 'answer 2'), (3, 'answer 3'), (4, 'answer 4'), (5, 'answer 5')], default=1, verbose_name='nut_question2'),
        ),
        migrations.AddField(
            model_name='person',
            name='nut_question3',
            field=models.IntegerField(choices=[(1, 'answer 1'), (2, 'answer 2'), (3, 'answer 3'), (4, 'answer 4'), (5, 'answer 5')], default=1, verbose_name='nut_question3'),
        ),
        migrations.AddField(
            model_name='person',
            name='nut_question4',
            field=models.IntegerField(choices=[(1, 'answer 1'), (2, 'answer 2'), (3, 'answer 3'), (4, 'answer 4'), (5, 'answer 5')], default=1, verbose_name='nut_question4'),
        ),
        migrations.AddField(
            model_name='person',
            name='nut_question5',
            field=models.IntegerField(choices=[(1, 'answer 1'), (2, 'answer 2'), (3, 'answer 3'), (4, 'answer 4'), (5, 'answer 5')], default=1, verbose_name='nut_question5'),
        ),
        migrations.AddField(
            model_name='person',
            name='target_nutrition',
            field=models.CharField(default='stunting', max_length=40, verbose_name='target_nut'),
        ),
    ]
