# Generated by Django 2.2.5 on 2020-01-31 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0036_auto_20200131_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='nut_group',
            field=models.CharField(choices=[(1, 'children under 5'), (2, 'pregnant woman'), (3, 'adlescent girl'), (4, 'adult')], default='children under 5', max_length=200, verbose_name='nut_group'),
        ),
        migrations.CreateModel(
            name='DRI_aggr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=200)),
                ('protein', models.FloatField(default=0, verbose_name='protein')),
                ('vita', models.FloatField(default=0, verbose_name='Vit-A')),
                ('fe', models.FloatField(default=0, verbose_name='iron')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='record_date')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
