# Generated by Django 2.2.5 on 2020-02-14 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0037_auto_20200212_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fct',
            name='food_item_id',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='mycrop',
            name='myFCT',
            field=models.ForeignKey(default=436, on_delete=django.db.models.deletion.CASCADE, to='myApp.FCT', to_field='food_item_id'),
        ),
    ]
