# Generated by Django 2.2.5 on 2020-01-31 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0038_auto_20200131_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dri_aggr',
            name='group',
            field=models.CharField(default='children under 5', max_length=200, verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='person',
            name='target_pop',
            field=models.IntegerField(default=1, verbose_name='target population'),
        ),
    ]
