# Generated by Django 2.2.5 on 2020-02-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0039_auto_20200131_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='myProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_id', models.IntegerField(default=0)),
                ('aez_id', models.CharField(max_length=200)),
                ('conv_crop_grow_list', models.CharField(max_length=200)),
                ('conv_crop_sold_list', models.CharField(max_length=200)),
                ('person_id', models.IntegerField(default=0)),
                ('crop_id', models.IntegerField(default=0)),
            ],
        ),
    ]
