# Generated by Django 2.2.5 on 2020-02-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0040_auto_20200216_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='target_nutrition',
            field=models.CharField(choices=[('Stunting', 'Stunting'), ('Wasting', 'Wasting'), ('Anemia', 'Anemia'), ('Other', 'Other')], default='stunting', max_length=40, verbose_name='target_nut'),
        ),
    ]
