# Generated by Django 2.2.5 on 2020-02-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0040_myprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprogress',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='myprogress',
            name='aez_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='myprogress',
            name='conv_crop_grow_list',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='myprogress',
            name='conv_crop_sold_list',
            field=models.CharField(default='', max_length=200),
        ),
    ]
