# Generated by Django 2.2.5 on 2020-02-01 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0041_auto_20200201_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprogress',
            name='user_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
