# Generated by Django 2.2.5 on 2020-02-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0041_auto_20200217_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='energy',
            field=models.FloatField(default=0, verbose_name='energy'),
        ),
    ]
