# Generated by Django 2.2.5 on 2020-02-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0042_myprogress_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprogress',
            name='aez_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='myprogress',
            name='conv_crop_grow_list',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='myprogress',
            name='conv_crop_sold_list',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='myprogress',
            name='crop_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='myprogress',
            name='family_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='myprogress',
            name='person_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
