# Generated by Django 2.2.5 on 2020-02-18 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0043_dri_aggr_energy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dri_aggr',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dri_aggr',
            name='created_by',
        ),
    ]
