# Generated by Django 2.2.5 on 2020-02-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0043_auto_20200201_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprogress',
            name='family_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
