# Generated by Django 2.2.5 on 2020-02-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0044_auto_20200201_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='avail_farm',
            field=models.IntegerField(default=0, verbose_name='available_farm'),
        ),
        migrations.AddField(
            model_name='crop',
            name='avail_market',
            field=models.IntegerField(default=0, verbose_name='available_market'),
        ),
        migrations.AddField(
            model_name='crop',
            name='avail_new',
            field=models.IntegerField(default=0, verbose_name='available_new'),
        ),
        migrations.AlterField(
            model_name='myprogress',
            name='conv_crop_grow_list',
            field=models.CharField(blank=True, default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='myprogress',
            name='conv_crop_sold_list',
            field=models.CharField(blank=True, default='0', max_length=200),
        ),
    ]
