# Generated by Django 2.2.5 on 2020-02-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0045_person_energy'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='portion_size',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='fct',
            name='portion_size',
            field=models.IntegerField(default=100),
        ),
    ]
