# Generated by Django 2.2.5 on 2020-02-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0046_auto_20200219_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='target_nutrition',
            field=models.CharField(choices=[('stunting', 'stunting'), ('wasting', 'wasting'), ('anemia', 'anemia'), ('other', 'other')], default='stunting', max_length=40, verbose_name='target_nut'),
        ),
    ]
