# Generated by Django 2.2.11 on 2020-03-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0047_auto_20200223_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fct',
            name='portion_size',
            field=models.IntegerField(default=30),
        ),
    ]
