# Generated by Django 2.2.5 on 2020-02-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0047_auto_20200202_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprogress',
            name='crop_list',
            field=models.CharField(blank=True, default='0', max_length=200),
        ),
    ]
