# Generated by Django 2.2.5 on 2020-02-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0048_myprogress_crop_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprogress',
            name='user_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
