# Generated by Django 2.2.5 on 2020-02-05 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0049_auto_20200202_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='country_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.Countries'),
        ),
    ]
