# Generated by Django 2.2.11 on 2020-03-24 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0051_mystatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mystatus',
            name='myLocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.Community'),
        ),
    ]
