# Generated by Django 2.2.11 on 2020-03-25 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0052_auto_20200324_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='name')),
                ('country', models.CharField(max_length=200)),
                ('region', models.CharField(blank=True, max_length=200)),
                ('province', models.CharField(blank=True, max_length=200)),
                ('community', models.CharField(blank=True, max_length=200)),
                ('AEZ_id', models.CharField(max_length=200)),
                ('stunting_rate', models.IntegerField(blank=True, default=0)),
                ('wasting_rate', models.IntegerField(blank=True, default=0)),
                ('anemia_rate', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='record_date')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='mystatus',
            old_name='crop_Community',
            new_name='myCrop',
        ),
        migrations.RenameField(
            model_name='mystatus',
            old_name='crop_Individual',
            new_name='myDiet',
        ),
        migrations.RemoveField(
            model_name='crop_individual',
            name='myCommunity',
        ),
        migrations.RemoveField(
            model_name='crop_subnational',
            name='myCommunity',
        ),
        migrations.RemoveField(
            model_name='person',
            name='myCommunity',
        ),
        migrations.AlterField(
            model_name='mystatus',
            name='curr_User',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='mystatus',
            name='myLocation',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.DeleteModel(
            name='Community',
        ),
        migrations.AddField(
            model_name='crop_individual',
            name='myLocation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myApp.Location'),
        ),
        migrations.AddField(
            model_name='crop_subnational',
            name='myLocation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myApp.Location'),
        ),
        migrations.AddField(
            model_name='person',
            name='myLocation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myApp.Location'),
        ),
    ]
