# Generated by Django 2.2.11 on 2020-03-26 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0057_auto_20200325_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='myDRI',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.DRI'),
        ),
        migrations.AlterField(
            model_name='person',
            name='myLocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.Location'),
        ),
    ]
