# Generated by Django 2.2.11 on 2020-03-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0059_location_mycountry'),
    ]

    operations = [
        migrations.AddField(
            model_name='mystatus',
            name='myTarget',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
