# Generated by Django 2.2.11 on 2020-03-28 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0060_mystatus_mytarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country_label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm_name_1', models.CharField(blank=True, max_length=200)),
                ('adm_name_2', models.CharField(blank=True, max_length=200)),
                ('adm_name_3', models.CharField(blank=True, max_length=200)),
                ('adm_name_4', models.CharField(blank=True, max_length=200)),
                ('adm_name_5', models.CharField(blank=True, max_length=200)),
                ('myCountry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.Countries')),
            ],
        ),
    ]
