# Generated by Django 2.2.11 on 2020-03-29 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0062_crop_individual_portion_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop_individual',
            old_name='portion_count',
            new_name='total_weight',
        ),
    ]
