# Generated by Django 2.2.11 on 2020-03-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0063_auto_20200329_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop_individual',
            name='portion_size',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='crop_individual',
            name='total_weight',
            field=models.IntegerField(default=0),
        ),
    ]
