# Generated by Django 2.2.11 on 2020-04-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0067_crop_individual_id_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='class_aggr',
        ),
        migrations.AddField(
            model_name='person',
            name='target_scope',
            field=models.IntegerField(default=0, verbose_name='target_scope'),
        ),
        migrations.AlterField(
            model_name='crop_individual',
            name='target_scope',
            field=models.IntegerField(default=0, verbose_name='target_scope'),
        ),
    ]
