# Generated by Django 2.2.5 on 2019-10-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_crop_diet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='crop_score',
            field=models.IntegerField(default=0, verbose_name='crop_score'),
        ),
    ]
