# Generated by Django 2.2.5 on 2019-10-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_crop_crop_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='food_wt_fe',
            field=models.FloatField(default=0, verbose_name='weight'),
        ),
        migrations.AddField(
            model_name='crop',
            name='food_wt_p',
            field=models.FloatField(default=0, verbose_name='weight'),
        ),
        migrations.AddField(
            model_name='crop',
            name='food_wt_va',
            field=models.FloatField(default=0, verbose_name='weight'),
        ),
    ]
