# Generated by Django 2.2.5 on 2019-10-02 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_auto_20191002_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='fe_s',
        ),
        migrations.RemoveField(
            model_name='family',
            name='protein_s',
        ),
        migrations.RemoveField(
            model_name='family',
            name='vita_s',
        ),
    ]
