# Generated by Django 2.2.5 on 2019-10-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_auto_20191002_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(choices=[(1, 'less than 6 mon'), (2, '6 mon to age 1'), (3, 'age 1 to 1.5'), (4, 'age 1.5 to 2'), (5, 'age 2 to 3'), (6, 'age 3 to 4'), (7, 'age 4 to 5'), (8, 'age 5 to 6'), (9, 'age 6 to 7'), (10, 'age 7 to 8'), (11, 'age 8 to 9'), (11, 'age 9 to 10'), (12, 'age 10 to 11'), (13, 'age 11 to 12'), (14, 'age 12 to 13'), (15, 'age 13 to 14'), (16, 'age 14 to 15'), (17, 'age 15 to 16'), (18, 'age 16 to 17'), (19, 'age 17 to 18'), (20, 'age 18 to 19'), (21, 'age 19 to 65'), (22, 'age 65 <= age')], default=1, verbose_name='age'),
        ),
    ]
