# Generated by Django 2.2.5 on 2019-10-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_auto_20191022_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='nutrition_target',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
