# Generated by Django 2.2.5 on 2019-10-31 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0019_auto_20191030_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='protein',
            field=models.FloatField(default=0, null=True, verbose_name='protein'),
        ),
    ]
