# Generated by Django 2.2.5 on 2019-11-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0023_auto_20191031_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='anemia_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='family',
            name='major_commodity',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='family',
            name='stunting_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='family',
            name='wasting_rate',
            field=models.IntegerField(default=0),
        ),
    ]
