# Generated by Django 2.2.5 on 2019-11-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0024_auto_20191101_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='target_pop',
            field=models.IntegerField(default=1, verbose_name='number'),
        ),
    ]
