# Generated by Django 2.2.5 on 2019-11-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0027_auto_20191101_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='nutrient_target',
            field=models.IntegerField(choices=[(1, 'protein'), (2, 'vita'), (3, 'iron')], default=1),
        ),
    ]
