# Generated by Django 2.2.5 on 2019-11-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0028_crop_nutrient_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='feas_DRI',
            field=models.IntegerField(choices=[(0, 'no for all'), (1, 'no for most target grp'), (2, 'yes for most target grp'), (3, 'yes for all')], default=0, verbose_name='feas_DRI'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='feas_DRI_a',
            field=models.IntegerField(choices=[(0, 'no for all'), (1, 'no for most target grp'), (2, 'yes for most target grp'), (3, 'yes for all')], default=0, verbose_name='feas_DRI_a'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='feas_DRI_f',
            field=models.IntegerField(choices=[(0, 'no for all'), (1, 'no for most target grp'), (2, 'yes for most target grp'), (3, 'yes for all')], default=0, verbose_name='feas_DRI_f'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='feas_DRI_p',
            field=models.IntegerField(choices=[(0, 'no for all'), (1, 'no for most target grp'), (2, 'yes for most target grp'), (3, 'yes for all')], default=0, verbose_name='feas_DRI_p'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='feas_soc_acceptable',
            field=models.IntegerField(choices=[(3, 'no for all'), (2, 'no for most target grp'), (1, 'yes for most target grp'), (0, 'yes for all')], default=0, verbose_name='feas_social_wo'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='feas_soc_acceptable_c5',
            field=models.IntegerField(choices=[(3, 'no for all'), (2, 'no for most target grp'), (1, 'yes for most target grp'), (0, 'yes for all')], default=0, verbose_name='feas_social_c5'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='feas_soc_acceptable_wo',
            field=models.IntegerField(choices=[(3, 'no for all'), (2, 'no for most target grp'), (1, 'yes for most target grp'), (0, 'yes for all')], default=0, verbose_name='feas_social_wo'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='feas_tech_service',
            field=models.IntegerField(choices=[(1, 'no'), (2, 'maybe no'), (3, 'maybe yes'), (4, 'yes / there is no need for it since beneficiaries already have enough skill')], default=0, verbose_name='feas_tech_service'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='nutrient_target',
            field=models.IntegerField(choices=[(1, 'protein'), (2, 'vit-a'), (3, 'iron')], default=1),
        ),
    ]
