# Generated by Django 2.2.5 on 2020-02-06 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0029_auto_20191113_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GID_0', models.CharField(max_length=200)),
                ('NAME_0', models.CharField(max_length=200)),
                ('GID_1', models.CharField(max_length=200)),
                ('NAME_1', models.CharField(max_length=200)),
                ('GID_2', models.CharField(max_length=200)),
                ('NAME_2', models.CharField(max_length=200)),
                ('GID_3', models.CharField(max_length=200)),
                ('NAME_3', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='myProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, unique=True)),
                ('user_name', models.CharField(default='', max_length=200)),
                ('family_id', models.IntegerField(blank=True, default=0, null=True)),
                ('aez_id', models.CharField(blank=True, default='', max_length=200)),
                ('conv_crop_grow_list', models.CharField(blank=True, default='0', max_length=200)),
                ('conv_crop_sold_list', models.CharField(blank=True, default='0', max_length=200)),
                ('crop_list', models.CharField(blank=True, default='0', max_length=200)),
                ('person_id', models.IntegerField(blank=True, default=0)),
                ('crop_id', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.AddField(
            model_name='crop',
            name='avail_type',
            field=models.IntegerField(default=1, verbose_name='available_farm'),
        ),
        migrations.AddField(
            model_name='family',
            name='conv_crop_grow',
            field=models.CharField(default='0', max_length=1000),
        ),
        migrations.AddField(
            model_name='family',
            name='conv_crop_sold',
            field=models.CharField(default='0', max_length=1000),
        ),
        migrations.AddField(
            model_name='person',
            name='nut_group',
            field=models.CharField(choices=[('children under 5', 'children under 5'), ('pregnant woman', 'pregnant woman'), ('adlescent girl', 'adlescent girl'), ('adult', 'adult')], default='children under 5', max_length=200, verbose_name='nut_group'),
        ),
        migrations.AddField(
            model_name='person',
            name='nut_question1',
            field=models.IntegerField(choices=[(1, 'answer 1'), (2, 'answer 2'), (3, 'answer 3'), (4, 'answer 4'), (5, 'answer 5')], default=1, verbose_name='nut_question1'),
        ),
        migrations.AddField(
            model_name='person',
            name='nut_question2',
            field=models.IntegerField(choices=[(1, 'answer 1'), (2, 'answer 2'), (3, 'answer 3'), (4, 'answer 4'), (5, 'answer 5')], default=1, verbose_name='nut_question2'),
        ),
        migrations.AddField(
            model_name='person',
            name='nut_question3',
            field=models.IntegerField(choices=[(1, 'answer 1'), (2, 'answer 2'), (3, 'answer 3'), (4, 'answer 4'), (5, 'answer 5')], default=1, verbose_name='nut_question3'),
        ),
        migrations.AddField(
            model_name='person',
            name='nut_question4',
            field=models.IntegerField(choices=[(1, 'answer 1'), (2, 'answer 2'), (3, 'answer 3'), (4, 'answer 4'), (5, 'answer 5')], default=1, verbose_name='nut_question4'),
        ),
        migrations.AddField(
            model_name='person',
            name='nut_question5',
            field=models.IntegerField(choices=[(1, 'answer 1'), (2, 'answer 2'), (3, 'answer 3'), (4, 'answer 4'), (5, 'answer 5')], default=1, verbose_name='nut_question5'),
        ),
        migrations.AddField(
            model_name='person',
            name='target_nutrition',
            field=models.CharField(default='stunting', max_length=40, verbose_name='target_nut'),
        ),
        migrations.AlterField(
            model_name='family',
            name='anemia_rate',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='family',
            name='nutrition_target',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='family',
            name='stunting_rate',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='family',
            name='wasting_rate',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='target_pop',
            field=models.IntegerField(default=1, verbose_name='target population'),
        ),
        migrations.CreateModel(
            name='DRI_aggr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(default='children under 5', max_length=200, verbose_name='group')),
                ('protein', models.FloatField(default=0, verbose_name='protein')),
                ('vita', models.FloatField(default=0, verbose_name='Vit-A')),
                ('fe', models.FloatField(default=0, verbose_name='iron')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='record_date')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Crop_Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('GID_1', models.CharField(max_length=200)),
                ('FCT_id', models.IntegerField(default=1)),
                ('food_grp_id', models.IntegerField(default=1)),
                ('food_item_id', models.IntegerField(default=1)),
                ('Food_grp', models.CharField(max_length=200)),
                ('Food_name', models.CharField(max_length=200)),
                ('suitable_class', models.IntegerField(default=1)),
                ('Hrv_strt', models.IntegerField(default=1)),
                ('Hrv_end', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='record_date')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Crop_AEZ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('FCT_id', models.IntegerField(default=1)),
                ('food_grp_id', models.IntegerField(default=1)),
                ('food_item_id', models.IntegerField(default=1)),
                ('Food_grp', models.CharField(max_length=200)),
                ('Food_name', models.CharField(max_length=200)),
                ('Crop_ref', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='record_date')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='family',
            name='country_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.Countries'),
        ),
    ]
