# Generated by Django 2.2.5 on 2020-02-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0034_auto_20200206_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='nut_group',
            field=models.CharField(choices=[('children under 5', 'children under 5'), ('pregnant women', 'pregnant women'), ('adlescent girl', 'adlescent girl'), ('adult', 'adult')], default='children under 5', max_length=200, verbose_name='nut_group'),
        ),
    ]
