# Generated by Django 2.2.5 on 2020-02-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0035_auto_20200206_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='myCrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FCT_id', models.IntegerField(default=1)),
                ('selected_status', models.IntegerField(default=0, verbose_name='mon01_prod')),
                ('m1', models.IntegerField(default=0, verbose_name='mon01_prod')),
                ('m2', models.IntegerField(default=0, verbose_name='mon02_prod')),
                ('m3', models.IntegerField(default=0, verbose_name='mon03_prod')),
                ('m4', models.IntegerField(default=0, verbose_name='mon04_prod')),
                ('m5', models.IntegerField(default=0, verbose_name='mon05_prod')),
                ('m6', models.IntegerField(default=0, verbose_name='mon06_prod')),
                ('m7', models.IntegerField(default=0, verbose_name='mon07_prod')),
                ('m8', models.IntegerField(default=0, verbose_name='mon08_prod')),
                ('m9', models.IntegerField(default=0, verbose_name='mon09_prod')),
                ('m10', models.IntegerField(default=0, verbose_name='mon10_prod')),
                ('m11', models.IntegerField(default=0, verbose_name='mon11_prod')),
                ('m12', models.IntegerField(default=0, verbose_name='mon12_prod')),
            ],
        ),
        migrations.RenameField(
            model_name='crop_aez',
            old_name='country',
            new_name='AEZ_id',
        ),
        migrations.AlterField(
            model_name='dri_aggr',
            name='nut_group',
            field=models.CharField(default='children 6 to 59 month', max_length=200, verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nut_group',
            field=models.CharField(choices=[('children under 5', 'children 6 to 59 month'), ('pregnant women', 'pregnant women'), ('adlescent girl', 'adlescent girl'), ('adult', 'adult')], default='children 6 to 59 month', max_length=200, verbose_name='nut_group'),
        ),
    ]
