# Generated by Django 2.2.5 on 2020-02-12 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0036_auto_20200211_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycrop',
            name='FCT_id',
        ),
        migrations.AddField(
            model_name='mycrop',
            name='myFCT',
            field=models.ForeignKey(default=11436, on_delete=django.db.models.deletion.CASCADE, to='myApp.FCT', to_field='FCT_id'),
        ),
        migrations.AddField(
            model_name='mycrop',
            name='myFamily',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myApp.Family'),
        ),
        migrations.AlterField(
            model_name='fct',
            name='FCT_id',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
