# Generated by Django 2.2.5 on 2020-02-16 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0039_countries_aez_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop_aez',
            name='Crop_ref',
        ),
        migrations.RemoveField(
            model_name='crop_aez',
            name='FCT_id',
        ),
        migrations.RemoveField(
            model_name='crop_aez',
            name='Food_grp',
        ),
        migrations.RemoveField(
            model_name='crop_aez',
            name='Food_name',
        ),
        migrations.RemoveField(
            model_name='crop_aez',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='crop_aez',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='crop_aez',
            name='food_grp_id',
        ),
        migrations.RemoveField(
            model_name='crop_aez',
            name='food_item_id',
        ),
        migrations.AddField(
            model_name='crop_aez',
            name='myFCT',
            field=models.ForeignKey(default=436, on_delete=django.db.models.deletion.CASCADE, to='myApp.FCT', to_field='food_item_id'),
        ),
    ]
