# Generated by Django 2.2.5 on 2020-02-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0042_family_energy'),
    ]

    operations = [
        migrations.AddField(
            model_name='dri_aggr',
            name='energy',
            field=models.FloatField(default=0, verbose_name='nut_energy'),
        ),
    ]
