# Generated by Django 2.2.5 on 2020-02-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0044_auto_20200218_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='energy',
            field=models.FloatField(default=0, verbose_name='protein'),
        ),
    ]
