# Generated by Django 2.2.11 on 2020-03-23 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0048_auto_20200316_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='crop_aez',
            name='myFCT',
        ),
        migrations.RemoveField(
            model_name='crop_region',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='DRI',
        ),
        migrations.DeleteModel(
            name='DRI_aggr',
        ),
        migrations.DeleteModel(
            name='DRI_women',
        ),
        migrations.RemoveField(
            model_name='family',
            name='country_test',
        ),
        migrations.RemoveField(
            model_name='family',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='mycrop',
            name='myFCT',
        ),
        migrations.RemoveField(
            model_name='mycrop',
            name='myFamily',
        ),
        migrations.DeleteModel(
            name='myProgress',
        ),
        migrations.RemoveField(
            model_name='person',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Crop',
        ),
        migrations.DeleteModel(
            name='Crop_AEZ',
        ),
        migrations.DeleteModel(
            name='Crop_Region',
        ),
        migrations.DeleteModel(
            name='Family',
        ),
        migrations.DeleteModel(
            name='FCT',
        ),
        migrations.DeleteModel(
            name='myCrop',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
