# Generated by Django 2.2.11 on 2020-03-25 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0054_auto_20200325_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop_subnational',
            name='crop_feas',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.Crop_Feasibility'),
        ),
        migrations.AlterField(
            model_name='crop_subnational',
            name='myFCT',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.FCT', to_field='food_item_id'),
        ),
        migrations.AlterField(
            model_name='crop_subnational',
            name='myLocation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.Location'),
        ),
    ]
