# Generated by Django 2.2.11 on 2020-03-27 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0058_auto_20200326_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='myCountry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.Countries'),
        ),
    ]
