# Generated by Django 2.2.11 on 2020-03-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0061_country_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop_individual',
            name='portion_count',
            field=models.IntegerField(default=100),
        ),
    ]
