# Generated by Django 2.2.11 on 2020-04-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0064_auto_20200329_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop_individual',
            name='m10_buy',
        ),
        migrations.RemoveField(
            model_name='crop_individual',
            name='m10_prod',
        ),
        migrations.RemoveField(
            model_name='crop_individual',
            name='m11_buy',
        ),
        migrations.RemoveField(
            model_name='crop_individual',
            name='m11_prod',
        ),
        migrations.RemoveField(
            model_name='crop_individual',
            name='m12_buy',
        ),
        migrations.RemoveField(
            model_name='crop_individual',
            name='m12_prod',
        ),
        migrations.RemoveField(
            model_name='crop_individual',
            name='m1_buy',
        ),
        migrations.RemoveField(
            model_name='crop_individual',
            name='m1_prod',
        ),
        migrations.RemoveField(
            model_name='crop_individual',
            name='m2_buy',
        ),
        migrations.RemoveField(
            model_name='crop_individual',
            name='m2_prod',
        ),
        migrations.RemoveField(
            model_name='crop_individual',
            name='m3_buy',
        ),
        migrations.RemoveField(
            model_name='crop_individual',
            name='m3_prod',
        ),
        migrations.RemoveField(
            model_name='crop_individual',
            name='m4_buy',
        ),
        migrations.RemoveField(
            model_name='crop_individual',
            name='m4_prod',
        ),
        migrations.RemoveField(
            model_name='crop_individual',
            name='m5_buy',
        ),
        migrations.RemoveField(
            model_name='crop_individual',
            name='m5_prod',
        ),
        migrations.RemoveField(
            model_name='crop_individual',
            name='m6_buy',
        ),
        migrations.RemoveField(
            model_name='crop_individual',
            name='m6_prod',
        ),
        migrations.RemoveField(
            model_name='crop_individual',
            name='m7_buy',
        ),
        migrations.RemoveField(
            model_name='crop_individual',
            name='m7_prod',
        ),
        migrations.RemoveField(
            model_name='crop_individual',
            name='m8_buy',
        ),
        migrations.RemoveField(
            model_name='crop_individual',
            name='m8_prod',
        ),
        migrations.RemoveField(
            model_name='crop_individual',
            name='m9_buy',
        ),
        migrations.RemoveField(
            model_name='crop_individual',
            name='m9_prod',
        ),
        migrations.AddField(
            model_name='crop_individual',
            name='count_buy',
            field=models.IntegerField(default=0, verbose_name='count_buy'),
        ),
        migrations.AddField(
            model_name='crop_individual',
            name='count_prod',
            field=models.IntegerField(default=0, verbose_name='count_prod'),
        ),
        migrations.AddField(
            model_name='crop_individual',
            name='month',
            field=models.IntegerField(default=0, verbose_name='month'),
        ),
    ]
