# Generated by Django 2.2.11 on 2020-04-06 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0065_auto_20200404_0250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop_individual',
            old_name='class_aggr',
            new_name='target_scope',
        ),
    ]
