# Generated by Django 2.2.11 on 2020-04-13 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0068_auto_20200406_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME_0', models.CharField(max_length=200)),
                ('GID_0', models.CharField(max_length=200)),
                ('Year', models.IntegerField(default=0, verbose_name='Year')),
                ('Age_class', models.CharField(max_length=50)),
                ('Age_class_id', models.IntegerField(default=0, verbose_name='Age_Class')),
                ('share_Pop', models.FloatField(default=0)),
                ('share_Preg', models.FloatField(default=0)),
                ('share_BF', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='target_scope',
            field=models.IntegerField(default=0, verbose_name='class_aggr'),
        ),
    ]
