@startuml
left to right direction

title step7: diet planning

entity crop_list {
  -id
  --
  crop_id
  m1_availability
  m2_availability
  m3_availability
  m4_availability
  m5_availability
  m6_availability
  m7_availability
  m8_availability
  m9_availability
  m10_availability
  m11_availability
  m12_availability
}
entity crop_selected {
  -id
  --
  crop_id
  month
  volume
  energy
  protein
  vita
  iron
}


crop_list <-- crop_selected:"1:作物リストを参照"
crop_list --> crop_selected:"2:作物を選択・保存"

crop_selected --> crop_vol:"3:摂取量を調整"
crop_selected <-- crop_vol:"4:摂取量を保存"



@enduml
