@startuml
left to right direction

title step2: location infor --> suitable crop list

actor :user: as user
actor :system: as admin
actor :table_AEZ: as table1
actor :table_Country: as table2

  package "User interface" <<Rect>> {
      user --> (user info):"1"
      (user info) --> admin:"1"
      user <-- (user info):"1 auth"
      (user info) <-- admin:"1 auth"
      user --> (location info):"2"
      (location info) --> admin:"2"
  }

  package "Backend DB" {
    admin --> (location):"2"
    (location) --> table2:"2"
    table2 <-> table1
    (suitable crop) <-- table1
  }


@enduml
